### PR TITLE
Target definition as file

### PR DESCRIPTION
**Pull request by vogella**

### CODE REVIEW

**Comment by vogella** [comment]
@laeubi If I switch to the new <file> definition (which I think you developed) for the target file, the build fails. Anything wrong in my setup or is their a bug in Tycho?

**Comment by laeubi** [comment]
The <file> must point to an actual physical file (probably something like ${project.basedir}/mytarget.target} or some similar maven magic). In your example you only give a file name that most probably is resolved to the working directory of the maven call or something,

**Comment by vogella** [comment]
Thanks for the reply, but also does not work: <file>${project.basedir}/../target-platform/target-platform.target</file>

[ERROR] Setting target failed: target definition file '/home/vogella/git/eclipse4book/com.example.e4.rcp/../target-platform/target-platform.target' not found in project 'Rcp'. -> [Help 1]
Even though cat '/home/vogella/git/eclipse4book/com.example.e4.rcp/../target-platform/target-platform.target' works fine.

**Comment by laeubi** [comment]
Don't know if it matters here but you are using a old tycho-pomless extension, you better should upgrade to 2.3.0 also.

**Comment by laeubi** [comment]
BTW if you don't force push its a lot easier to follow what has changed between commits! Github allows to squasch all changes into one big change before merging it to the master branch afterwards.

**Comment by laeubi** [comment]
BTW you can set a Breakpoint at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.setTarget(TargetPlatformConfiguration, MavenSession, MavenProject, Xpp3Dom)
to see why your target is rejected.

**Comment by laeubi** [comment]
I tried to build this locally and it currently fails with:

```
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.vogella.tycho:releng:1.0.0-SNAPSHOT (/tmp/eclipse4book/pom.xml) has 3 errors
[ERROR]     Child module /tmp/eclipse4book/com.example.e4.rcp of /tmp/eclipse4book/pom.xml does not exist
[ERROR]     Child module /tmp/eclipse4book/com.example.e4.feature of /tmp/eclipse4book/pom.xml does not exist
[ERROR]     Child module /tmp/eclipse4book/com.example.e4.product of /tmp/eclipse4book/pom.xml does not exist

```

**Comment by laeubi** [comment]
I remvoed the missing modules and it seems that your expression expands to '/tmp/eclipse4book/com.vogella.tasks.ui/../target-platform/target-platform.target'

Using  ` <file>../target-platform/target-platform.target</file>` works here.

**Comment by vogella** [comment]
Strange, how did I merge this????

Thanks, @laeubi using <file>../target-platform/target-platform.target</file> works fine. 

What is recommended? Using a file reference or a target definition project? Or does it not matter?

**Comment by laeubi** [comment]
Improved error output https://git.eclipse.org/r/c/tycho/org.eclipse.tycho/+/178903 gives now:

`[ERROR] Setting target failed: target definition file '/tmp/eclipse4book/com.vogella.tasks.ui/tmp/eclipse4book/com.vogella.tasks.ui/../target-platform/target-platform.target' not found for project '[bundle] Ui'. -> [Help 1]`

> What is recommended? Using a file reference or a target definition project? Or does it not matter?

Whatever suits your needs.  **Target definition artifact** is usually required if you plan to use target files across projects and thus deploy them e.g. into nexus (the target is then a first class maven-artifact).
If your project is selfcontained, a **Target definition file** might me more suitable as it doesn't matter where the target is located in the project tree and you don't even need to define a module for it (the target is more a configuration file input then).

**Comment by vogella** [comment]
Thanks @laeubi

**Pull request merged**
